apiVersion: v1
kind: Service
metadata:
  name: httpserver
  namespace: cloudnative 
spec:
  selector:
    app: httpserver
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080


