apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: testinit
        image: busybox
        command: ["sh","-c","echo initconainer"]
      containers:
      - name: httpserver
        image: wuyongmax/httpserver
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c","sleep 4"]
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 30"]
        volumeMounts:
        - name: regred
          mountPath: "/etc/foo"
      volumes:
      - name: regred
        secret:
          secretName: regred
          optional: false
